MethodsAactions,annotated_source_code,application_traceCcorrectionsEerror_highlight_available?,exception_id,exception_inspect,exception_name,exception_traceFfailures,file_name,framework_trace,full_traceHhas_cause?,has_corrections?Lline_numberMmessageNnewOoriginal_messageRrescue_response?,rescue_template,routing_error?Sshow?,source_extracts,source_to_show_id,status_code,status_code_for_exception,sub_template_messageTtemplate_error?,trace_to_show,tracesUunwrapped_exceptionAttributes[R]backtrace_cleaner[R]exception[R]exception_class_name[R]wrapped_causesClass Public methodsnew(backtrace_cleaner, exception)LinkSource:show|on GitHub# File actionpack/lib/action_dispatch/middleware/exception_wrapper.rb, line 50definitialize(backtrace_cleaner,exception)@backtrace_cleaner=backtrace_cleaner@exception_class_name=exception.class.name@wrapped_causes=wrapped_causes_for(exception,backtrace_cleaner)@exception=exceptionifexception.is_a?(SyntaxError)@exception=ActiveSupport::SyntaxErrorProxy.new(exception)end@backtrace=build_backtraceendstatus_code_for_exception(class_name)LinkSource:show|on GitHub# File actionpack/lib/action_dispatch/middleware/exception_wrapper.rb, line 175defself.status_code_for_exception(class_name)Rack::Utils.status_code(@@rescue_responses[class_name])endInstance Public methodsactions()LinkSource:show|on GitHub# File actionpack/lib/action_dispatch/middleware/exception_wrapper.rb, line 101defactionsActiveSupport::ActionableError.actions(@exception)endannotated_source_code()LinkSource:show|on GitHub# File actionpack/lib/action_dispatch/middleware/exception_wrapper.rb, line 113defannotated_source_codeifexception.respond_to?(:annotated_source_code)exception.annotated_source_codeelse[]endendapplication_trace()LinkSource:show|on GitHub# File actionpack/lib/action_dispatch/middleware/exception_wrapper.rb, line 135defapplication_traceclean_backtrace(:silent)endcorrections()LinkSource:show|on GitHub# File actionpack/lib/action_dispatch/middleware/exception_wrapper.rb, line 89defcorrections@exception.correctionsenderror_highlight_available?()LinkSource:show|on GitHub# File actionpack/lib/action_dispatch/middleware/exception_wrapper.rb, line 204deferror_highlight_available?# ErrorHighlight.spot with backtrace_location keyword is available since# error_highlight 0.4.0defined?(ErrorHighlight)&&Gem::Version.new(ErrorHighlight::VERSION)>=Gem::Version.new("0.4.0")endexception_id()LinkSource:show|on GitHub# File actionpack/lib/action_dispatch/middleware/exception_wrapper.rb, line 234defexception_idexception.object_idendexception_inspect()LinkSource:show|on GitHub# File actionpack/lib/action_dispatch/middleware/exception_wrapper.rb, line 230defexception_inspectexception.inspectendexception_name()LinkSource:show|on GitHub# File actionpack/lib/action_dispatch/middleware/exception_wrapper.rb, line 222defexception_nameexception.cause.class.to_sendexception_trace()LinkSource:show|on GitHub# File actionpack/lib/action_dispatch/middleware/exception_wrapper.rb, line 129defexception_tracetrace=application_tracetrace=framework_traceiftrace.empty?&&!silent_exceptions.include?(@exception_class_name)traceendfailures()LinkSource:show|on GitHub# File actionpack/lib/action_dispatch/middleware/exception_wrapper.rb, line 77deffailures@exception.failuresendfile_name()LinkSource:show|on GitHub# File actionpack/lib/action_dispatch/middleware/exception_wrapper.rb, line 93deffile_name@exception.file_nameendframework_trace()LinkSource:show|on GitHub# File actionpack/lib/action_dispatch/middleware/exception_wrapper.rb, line 139defframework_traceclean_backtrace(:noise)endfull_trace()LinkSource:show|on GitHub# File actionpack/lib/action_dispatch/middleware/exception_wrapper.rb, line 143deffull_traceclean_backtrace(:all)endhas_cause?()LinkSource:show|on GitHub# File actionpack/lib/action_dispatch/middleware/exception_wrapper.rb, line 73defhas_cause?@exception.causeendhas_corrections?()LinkSource:show|on GitHub# File actionpack/lib/action_dispatch/middleware/exception_wrapper.rb, line 81defhas_corrections?@exception.respond_to?(:original_message)&&@exception.respond_to?(:corrections)endline_number()LinkSource:show|on GitHub# File actionpack/lib/action_dispatch/middleware/exception_wrapper.rb, line 97defline_number@exception.line_numberendmessage()LinkSource:show|on GitHub# File actionpack/lib/action_dispatch/middleware/exception_wrapper.rb, line 226defmessageexception.messageendoriginal_message()LinkSource:show|on GitHub# File actionpack/lib/action_dispatch/middleware/exception_wrapper.rb, line 85deforiginal_message@exception.original_messageendrescue_response?()LinkSource:show|on GitHub# File actionpack/lib/action_dispatch/middleware/exception_wrapper.rb, line 194defrescue_response?@@rescue_responses.key?(exception.class.name)endrescue_template()LinkSource:show|on GitHub# File actionpack/lib/action_dispatch/middleware/exception_wrapper.rb, line 121defrescue_template@@rescue_templates[@exception_class_name]endrouting_error?()LinkSource:show|on GitHub# File actionpack/lib/action_dispatch/middleware/exception_wrapper.rb, line 61defrouting_error?@exception.is_a?(ActionController::RoutingError)endshow?(request)LinkSource:show|on GitHub# File actionpack/lib/action_dispatch/middleware/exception_wrapper.rb, line 179defshow?(request)# We're treating `nil` as "unset", and we want the default setting to be `:all`.# This logic should be extracted to `env_config` and calculated once.config=request.get_header("action_dispatch.show_exceptions")caseconfigwhen:nonefalsewhen:rescuablerescue_response?elsetrueendendsource_extracts()LinkSource:show|on GitHub# File actionpack/lib/action_dispatch/middleware/exception_wrapper.rb, line 198defsource_extractsbacktrace.mapdo|trace|extract_source(trace)endendsource_to_show_id()LinkSource:show|on GitHub# File actionpack/lib/action_dispatch/middleware/exception_wrapper.rb, line 218defsource_to_show_id(traces[trace_to_show].first||{})[:id]endstatus_code()LinkSource:show|on GitHub# File actionpack/lib/action_dispatch/middleware/exception_wrapper.rb, line 125defstatus_codeself.class.status_code_for_exception(unwrapped_exception.class.name)endsub_template_message()LinkSource:show|on GitHub# File actionpack/lib/action_dispatch/middleware/exception_wrapper.rb, line 69defsub_template_message@exception.sub_template_messageendtemplate_error?()LinkSource:show|on GitHub# File actionpack/lib/action_dispatch/middleware/exception_wrapper.rb, line 65deftemplate_error?@exception.is_a?(ActionView::Template::Error)endtrace_to_show()LinkSource:show|on GitHub# File actionpack/lib/action_dispatch/middleware/exception_wrapper.rb, line 210deftrace_to_showiftraces["Application Trace"].empty?&&rescue_template!="routing_error""Full Trace"else"Application Trace"endendtraces()LinkSource:show|on GitHub# File actionpack/lib/action_dispatch/middleware/exception_wrapper.rb, line 147deftracesapplication_trace_with_ids= []framework_trace_with_ids= []full_trace_with_ids= []full_trace.each_with_indexdo|trace,idx|trace_with_id= {exception_object_id:@exception.object_id,id:idx,trace:trace}ifapplication_trace.include?(trace)application_trace_with_ids<<trace_with_idelseframework_trace_with_ids<<trace_with_idendfull_trace_with_ids<<trace_with_idend{"Application Trace"=>application_trace_with_ids,"Framework Trace"=>framework_trace_with_ids,"Full Trace"=>full_trace_with_ids}endunwrapped_exception()LinkSource:show|on GitHub# File actionpack/lib/action_dispatch/middleware/exception_wrapper.rb, line 105defunwrapped_exceptionifwrapper_exceptions.include?(@exception_class_name)@exception.causeelse@exceptionendend